{
 "title": "Cloud Detailed Dashboard",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Resource Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "openstack_identity_projects" }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(openstack_glance_images)" }
   ]
  },
  {
   "title": "Flavors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_nova_flavors" }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(openstack_nova_total_vms)" }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_nova_total_vms)" }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_cinder_volumes" }
   ]
  },
  {
   "title": "Floating IPs Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_floating_ips" }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_networks" }
   ]
  },
  {
   "title": "Subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_subnets" }
   ]
  },
  {
   "title": "Total vCPU Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_max)"
    }
   ]
  },
  {
   "title": "Total vCPU Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_used)"
    }
   ]
  },
  {
   "title": "% vCPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_nova_limits_vcpus_used)/sum(openstack_nova_limits_vcpus_max*4))*100"
    }
   ]
  },
  {
   "title": "Total Memory Available (GiB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Total Memory Used (GiB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_memory_used)/ 1024 / 1024 / 1024 "
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_nova_memory_used_bytes)/sum(openstack_nova_memory_available_bytes))*100"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})-sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Nova agent status",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{adminState=\"enabled\"}"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "openstack_neutron_agent_state" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Overall memory usage (TiB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Memory in TiB" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_memory_max)/ 1024",
     "legendFormat": "memory in use"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "memory available"
    }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_used)",
     "legendFormat": "used vcpu cores"
    },
    { "expr": "sum(openstack_nova_vcpus)", "legendFormat": "total vcpu cores" }
   ]
  },
  {
   "title": "Keystone stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(openstack_identity_projects)",
     "legendFormat": "projects"
    },
    { "expr": "avg(openstack_identity_users)", "legendFormat": "users" },
    { "expr": "avg(openstack_identity_groups)", "legendFormat": "groups" }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks)",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups)",
     "legendFormat": "security groups"
    },
    { "expr": "avg(openstack_neutron_subnets)", "legendFormat": "subnets" }
   ]
  },
  {
   "title": "Glance Images",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(openstack_glance_images)", "legendFormat": "images" }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms)",
     "legendFormat": "running vms"
    },
    { "expr": "sum(openstack_nova_total_vms)", "legendFormat": "total vms" }
   ]
  }
 ]
}