{
 "title": "Unified Cloud Services Logs Monitoring",
 "description": "This dashboard ment to describe OpenStack cloud services logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "loki" },
   {
    "name": "Log_level",
    "label": "Log_level",
    "query": "info,error,fail,fatal,warning,debug"
   },
   { "name": "Host_Datasource", "query": "loki" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(libvirt_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nova-Compute logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=~\"/var/log/syslog\"} |~ \"((?i)nova-compute|(?)${Node})\" "
    }
   ]
  },
  {
   "title": "Cinder Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_cinder_api_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"${Log_level}\""
    }
   ]
  },
  {
   "title": "Masakari Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_placement_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"${Log_level}\""
    }
   ]
  },
  {
   "title": "Placement Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_placement_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"${Log_level}\""
    }
   ]
  },
  {
   "title": "Nova Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{﻿﻿﻿filename﻿﻿=~﻿﻿\"/openstack/log/.*_nova_api_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"﻿﻿﻿}﻿﻿﻿ |~ ﻿﻿﻿\"$Log_level\""
    }
   ]
  },
  {
   "title": "Neutron Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_neutron_server_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "Rabbit-MQ Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_rabbit_mq_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "Keystone Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_keystone_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "Horizon Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_horizon_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "Glance Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_glance_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "Heat-API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_heat_api_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"$Log_level\""
    }
   ]
  },
  {
   "title": "All-In-One Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |~ \"((?i)error|(?i)warning|(?i)fail)\""
    }
   ]
  },
  {
   "title": "Utility Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_utility_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"((?i)error|(?i)warning|(?i)fail|(?i)info)\""
    }
   ]
  },
  {
   "title": "Repo Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_repo_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"((?i)error|(?i)warning|(?i)fail|(?i)info)\""
    }
   ]
  },
  {
   "title": "Memcached Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "{filename=~\"/openstack/log/.*_memcached_container.*/syslog|/var/log/lxc-cache-prep-commands\\\\.log\"} |~ \"((?i)error|(?i)warning|(?i)fail|(?i)info)\""
    }
   ]
  }
 ]
}